# Generated by Django 4.2.2 on 2023-06-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_movies_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='arating',
            field=models.FloatField(default=0),
        ),
    ]
